name: Ticketmasterr
description: "Ticketmasterrr"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+6

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.0.0

  pdf: ^3.10.4
  printing: ^5.12.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  image: ^4.1.3
  path_provider: ^2.1.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # You need to REMOVE or COMMENT OUT the 'assets:' line if the folder doesn't exist
  # assets:
  #   - assets/